### ISSUE TITLE
创造模式下物品错位

### ISSUE THREAD

**Issue by sleepyard** [LasmGratel/FoodCraft-Reloaded#8]
1.12.2版本下，模组物品会在几乎所有的创造标签中出现。如：在沉浸工艺模组中生成了一系列苏打水等道具，在匠魂工具标签下生成一系列苏打水等道具

**Comment by LasmGratel** [comment]
感谢您的反馈。

实际上在最新的版本已经解决了这个问题。你可能使用了第一个测试版。
